export const FETCHING_DATA_PEOPLE = 'FETCHING_DATA_PEOPLE';
export const FETCHING_DATA_PEOPLE_SUCCESS = 'FETCHING_DATA_PEOPLE_SUCCESS';
export const FETCHING_DATA_PEOPLE_FILM = 'FETCHING_DATA_PEOPLE_FILM';

export const FETCHING_DATA_PEOPLE_FAILURE = 'FETCHING_DATA_PEOPLE_FAILURE';


export const FETCHING_DATA_MOVIES = 'FETCHING_DATA_MOVIES';
export const FETCHING_DATA_MOVIES_FAILURE = 'FETCHING_DATA_MOVIES_FAILURE';
export const FETCHING_DATA_MOVIES_SUCCESS = 'FETCHING_DATA_MOVIES_SUCCESS';
export const FETCHING_DATA_FILM_PEOPLE = 'FETCHING_DATA_FILM_PEOPLE';


export const FETCHING_DATA_INFO = 'FETCHING_DATA_INFO';
export const FETCHING_DATA_INFO_SUCCESS = 'FETCHING_DATA_INFO_SUCCESS';
export const FETCHING_DATA_INFO_FAILURE = 'FETCHING_DATA_INFO_FAILURE';
export const SET_SELECTED_CLASSES ='SET_SELECTED_CLASSES';
